language: node_js
dist: trusty
sudo: required
node_js: 6
script:
- npm run test

cache:
  directories:
  - node_modules
env:
  global:
  - CF_APP=text-to-speech-react
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: react
    repo: watson-developer-cloud/speech-to-text
notifications:
  email: false
